org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties

minecraft_version=26.1
minecraft_version_range=[26.1,26.2)
neo_version=26.1.0.1-beta
neo_version_range=[26.1.0.1-beta,)

## Mod Properties

mod_version=5.0
