modLoader="javafml"
loaderVersion="${loader_version_range}"
license="LGPL v3"
issueTrackerURL="https://github.com/XFactHD/PingHUD"

[[mods]]
    modId="pinghud"
    version="${mod_version}"
    displayName="PingHUD"
    displayTest="IGNORE_ALL_VERSION"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/pinghud"
    logoFile="logo.png"
    authors="XFactHD"
    description=''''''

[[dependencies.pinghud]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.pinghud]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
