modLoader="javafml"
loaderVersion="[1,)"
license="LGPL v3"
issueTrackerURL="https://github.com/XFactHD/PingHUD"

[[mods]]
    modId="pinghud"
    version="${mod_version}"
    displayName="PingHUD"
    displayURL="https://www.curseforge.com/minecraft/mc-mods/pinghud"
    logoFile="logo.png"
    authors="XFactHD"
    description=''''''
    
[[mixins]]
    config="pinghud.mixin.json"

[[dependencies.pinghud]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.pinghud]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
